use numpad for viewport navigation and token movement; fix ctrl to ce…
Kruptein/PlanarAlly pull request #569
Opened 2020-11-18 01:17 UTC by dthv

…nter viewport on origin

2020-11-18 14:08 UTC, Kruptein requested changes

2020-11-18 14:08 UTC, Kruptein commented on client/src/game/input/keyboard.ts
> +        } else if (event.keyCode == 101) {
for individual keys it's better to use `event.key` or `event.code`, `event.keycode` is deprecated but slightly easier to work with when using ranges like 37->40.  You can use something like https://keycode.info to find the correct strings.
In the case of numpad it's probably recommended to use event.code as that differentiates between number row and numpad. (you could also use event.location to differentiate)

2020-11-18 14:08 UTC, Kruptein commented on client/src/game/input/keyboard.ts
> +                targetY *= 1 / selection.length;
just use `/=` instead of `*= 1/`

2020-11-19 00:51 UTC, dthv commented
Thanks for the improvements, edited as requested. :slightly_smiling_face:

2020-11-19 11:05 UTC, merged