PublicName and dev options fixes
Kruptein/PlanarAlly pull request #685
Opened 2021-02-18 15:22 UTC by mischievous

Code to set a public hostname to be used when updating the invitation url by reading from server_config.cfg 
    "general -> publicName".  If the publicName is empty or does not exists it falls back to normal operation.

 Added code to planarally.py to display the warning about the template directory if not running in 
    dev mode.

2021-02-18 18:01 UTC, Kruptein requested changes
In general pretty good stuff, some minor things here and there.

Although this works perfectly as is, I would prefer it if you just provided the public name along with the room info when the session loads ("Room.Info.Set" to be exact).
This simply because the request is launched to the server on load anyway at this moment and would make the logic slightly more easy to reason about. Also there is no reason to expect this to actually change during gameplay as this will require a server restart anyway to fetch the new config value.

2021-02-20 15:06 UTC, mischievous commented on client/src/game/store.ts
> +        console.log(name);
Removed.

2021-02-20 15:07 UTC, mischievous commented on server/api/socket/room.py
> +    #
Removed

2021-02-20 15:20 UTC, mischievous commented on CHANGELOG.md
> +
Updated

2021-02-20 15:21 UTC, mischievous commented on server/api/socket/room.py
> +    if len (publicName) == 0:
Removed white space.

2021-02-20 15:21 UTC, mischievous commented on server/api/socket/room.py
> +    await sio.emit ( "Room.Info.PublicName.Set", str(publicName), room=sid, namespace=GAME_NS )
Removed white space.

2021-02-20 15:23 UTC, mischievous commented on server/server_config.cfg
> +publicName =
Done

2021-02-20 16:53 UTC, Kruptein commented on CHANGELOG.md
> +
This one seems to still be in a duplicate section

2021-02-20 16:53 UTC, Kruptein commented on server/api/socket/room.py
> +    #
This one is still there it sems

2021-02-20 19:13 UTC, mischievous commented on server/api/socket/room.py
> +    #
Gone now.

2021-02-20 22:11 UTC, merged